generic_roasts = [
    "You have termites in your smile.",
    "I wouldn't touch you with a thirty-nine-and-a-half-foot pole.",
    "You nauseate me.",
    "You're a bad banana with a greasy black peel.",
    "You're as charming as an eel.",
    "You're as cuddly as a cactus.",
    "Your brain is full of spiders.",
    "Your heart is full of unwashed socks.",
    "You've got garlic in your soul.",
    "You're about as useful as a chocolate teapot.",
    "Be grateful you can re-marry and get rid of that name.",
    "You're dumber than a bag of hammers.",
    "Go fly a kite with a hole in it.",
    "You're more disappointing than a bag of unsalted popcorn.",
    "Stop running around like a chicken with its head cut off.",
    "Shampoo has instructions because of you.",
    "You have the I.Q. of mayonnaise.",
    "Be thankful that mirrors can't laugh.",
    "Do you have enough makeup for both of your faces?",
    "Go suck a lemon.",
    "I fart in your general direction!",
    "Kiss my caboose.",
    "Your face makes onions cry.",
    "You whine like a mule.",
    "You're about as useful as a glass hammer.",
    "Go eat soap.",
    "You've already been forgotten about.",
    "If I throw a stick, will you go away?",
    "I would agree with you, but then we'd both be wrong.",
    "You're barely looking better than a rotting corpse.",
    "You've got the manners of a goat.",
    "Sarcasm is but one of my many talents, and you are very beautiful.",
    "The less I see of you, the more I like you.",
    "You're as useless as wet toilet paper.",
    "You're the worst of all my bad choices.",
    "You have such a swelled head, you must have your hats made in a tent factory.",
    "If you lived by your wits, you'd starve.",
    "You know the old gag, \"Your face could stop a clock?\" Well, yours would stop a sundial.",
    "You were born with a big handicap: your mouth.",
    "You're just one tile short of a succesful re-entry.",
    "Wow! Did that thought leave skid marks in your hat?",
    "Did you ever stop to think... and forget to start again?",
    "Do you trip over cordless phones too?",
    "Remember, socks first, then shoes.",
    "The softness of your muscles is only exceeded by the hardness of your head.",
    "You have a very striking face. How many times were you stricken?",
    "What's wrong with you? How about if I gave it to you alphabetically?",
    "Your speech reminds me of a steer— a point here and there, and a lot of bull in between.",
    "You are depriving some poor village of its idiot.",
    "If your brain was chocolate it wouldn't fill an M&M.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "I see the wheel is spinning, but the hamster looks dead.",
    "If you had another brain, it would be lonely.",
    "Your teeth could be used as a map of the Appalachian Mountains",
    "You could be an extra in 'The Walking Dead,' but even zombies have better fashion sense.",
    "If you were any more bland, they'd have to add salt to put you on the flavor map.",

]

names = [
    "Bean Pole",
    "Scumbag",
    "Wuss",
    "Goofball",
    "Ding-Dong",
    "Poser",
    "Toilet Bug",
    "Nitwit",
    "Bozo",
    "Lazy Bug",
    "Fart Smeller",
    "Vulture",
    "Dill Hole",
    "Brown-Noser",
    "Pea Brain",
    "Numbskull",
    "Dipstick",
    "Hobknocker",
    "Sucker",
    "Snake",
    "Imbecile",
    "Fishsticks",
    "Chump",
    "Cow Chip",
    "Boot Licker",
    "Party Pooper",
    "Halfwit",
    "Villain",
    "Spinach Chin",
    "Gutless Turd",
    "Nightcrawler",
    "Crackpot",
    "Degenerate",
    "Sewer Mouth",
    "Fool",
    "Wackadoo",
    "Real Wart",
    "Buffoon",
    "Shmuck",
    "Loon",
    "Jerk",
    "Cake Eater",
    "Pop Tart",
    "Dope",
    "Turd Burglar",
    "Clown",
    "Punk",
    "Dirt Bag",
    "Village Idiot",
    "Bum",
    "Simpleton",
    "Crybaby",
    "Lunkhead",
    "Moocher",
    "Rube",
    "Scoundrel",
    "Scrub",
    "Peon",
    "Axolotl",
    "Narwhal",
    "Capybara",
    "Penguin",
    "Sloth",
    "Wombat",
    "Manatee",
    "Kookaburra",
    "Red Panda",
    "Emperor Penguin",
    "Fennec Fox",
    "Baboon",
    "Pufferfish",
    "Koala",
    "Lemur",
    "Potbelly Pig",
    "Raccoon",
    "Turtle",
    "Alpaca",
    "Zebra",
    "Hedgehog",
    "Bongo",
    "Tapir",
    "Okapi",
    "Pangolin",
    "Flying Squirrel",
    "Chinchilla",
    "Llama",
    "Aye-Aye",
    "Dodo Bird",
    "Wallaby",
    "Spoonbill",
    "Tarsier",
    "Maned Wolf",
    "Blobfish",
    "Giant Tortoise",
    "Okapi",
    "Sea Cucumber",
    "Blue-footed Booby",
    "Wombat",
    "Pygmy Goat",
    "Numbat",
    "Sugar Glider",
    "Platypus",
    "Tapir",
    "Pangolin",
    "Spotted Cow",
    "Spoonbill",
    "Hummingbird",
    "Crab-eating Macaque",
    "Kinkajou",
    "Aardvark",
    "Dromedary Camel",
    "Manta Ray",
    "Sifaka",
    "Ring-tailed Lemur",
]

roast_templates = [
    "You look like a mix between a {} and a {}.",
    "Your hairstyle could only be rivaled by a {} who lost a bet.",
    "You’ve got the personality of a {} and the charm of a {}.",
    "Your outfit looks like it was inspired by a {} and a {} on a budget.",
    "You're the human equivalent of a {} that just met a {}.",
    "Your face looks like it could be used to scare a {} and a {} at once.",
    "You have the subtlety of a {} mixed with the grace of a {}.",
    "Your sense of style is a cross between a {} and a {} on laundry day.",
    "If awkwardness were an Olympic sport, you'd be coached by a {} and a {}.",
    "You’ve got the sense of humor of a {} and the creativity of a {}.",
    "You look like a walking ad for {} who just met a {}.",
    "You've got the grace of a {} and the intelligence of a {}.",
    "Your luck is about as good as a {} meeting a {} in the wild.",
    "Your social skills are as smooth as a {} arguing with a {}.",
    "You're as intimidating as a {} trying to scare a {}.",
    "Your smile could probably charm a {}, but not a {}.",
    "You’ve got the subtlety of a {} and the wit of a {}.",
    "You look like a {} that tried to transform into a {}, but failed.",
    "Your confidence level is somewhere between a {} and a {} at a talent show.",
    "You're about as approachable as a {} with a {} as a bodyguard.",
    "You’ve got the fashion sense of a {} and the allure of a {}.",
    "Your taste in movies is so bad, even a {} would cringe.",
    "You’ve got the romantic appeal of a {} with the charisma of a {}.",
    "You’re as mysterious as a {} in a room full of {}.",
    "Your sense of timing is as good as a {} arguing with a {} on stage.",
    "You look like a {} that lost a bet to a {}.",
    "You’ve got the athletic ability of a {} and the endurance of a {}.",
    "You’re about as graceful as a {} stumbling over a {}.",
    "Your wit is as sharp as a {} softened by a {}.",
    "You're as emotionally available as a {} locked in a {}.",
    "You’re as charming as a {} with a fear of {}.",
    "You look like a {} trying to be a {} for Halloween.",
    "You’ve got the confidence of a {} who just got scolded by a {}.",
    "Your jokes hit as hard as a {} hitting a {} with a pillow.",
    "You’ve got the charisma of a {} and the charm of a {} trying to be cool.",
    "You’ve got the elegance of a {} and the refinement of a {}.",
    "Your sense of self is as solid as a {} balancing on a {}.",
    "You’ve got the swagger of a {} with the social grace of a {}.",
    "Your taste in friends is as questionable as a {} befriending a {}.",
    "You’re as reliable as a {} in a {}-only restaurant.",
    "You’ve got the relatability of a {} with the warmth of a {}.",
    "Your problem-solving skills are about as useful as a {} in a {} factory.",
    "You have the perspective of a {} mixed with the empathy of a {}.",
    "You look like the kind of person who'd ask a {} for fashion advice.",
    "You’re as good at communication as a {} trapped in a {} convention.",
    "You’ve got the culinary skills of a {} and the palate of a {}.",
    "You’re as memorable as a {} with a really forgettable {}.",
    "Your decision-making skills are on par with a {} chasing a {}.",
    "You’re as unpredictable as a {} racing a {} down a hill.",
    "Your attention span is like a {} distracted by a {}.",
    "You’ve got the insight of a {} and the wisdom of a {} at a party.",
    "You’ve got the same charm as a {} but with the likeability of a {}.",
    "Your self-awareness is as sharp as a {} at a {} convention.",
    "You’ve got the athleticism of a {} and the speed of a {} with a limp.",
    "Your speaking skills are as polished as a {} yelling at a {}.",
    "You're as inspiring as a {} on a Monday morning.",
    "Your loyalty is like a {} eyeing a {} buffet.",
    "You're as dependable as a {} giving directions to a {}.",
    "Your kindness is as genuine as a {} selling a {} to a stranger.",
    "Your outlook on life is as bright as a {} in a {} store.",
    "Your talent level matches that of a {} in a {} competition.",
    "You're as sharp as a {} with a hangover.",
    "You have the presence of a {} in a room full of {}.",
    "You're as calm as a {} surrounded by a pack of {}.",
    "You’re as reliable as a {} planning a {} surprise party.",
    "You look like a {} dressed as a {} for Halloween.",
    "You have the wisdom of a {} on a roller coaster.",
    "You’re about as approachable as a {} covered in {}s.",
    "Your social awareness rivals that of a {} at a {} parade.",
    "You’re as well-liked as a {} singing karaoke to a {} audience.",
    "You’re as trustworthy as a {} selling {} in an alley.",
    "You have the energy of a {} and the focus of a {} during nap time.",
    "Your self-control is on par with a {} in a room full of {}s.",
    "You're as motivational as a {} at a {} funeral.",
    "Your life advice sounds like it came from a {} in a {} seminar.",
    "You're as original as a {} at a {} convention.",
    "Your priorities are as well-placed as a {} in a {}'s wardrobe.",
    "You have the observational skills of a {} in a {} field."
]