name: Log Github Actions

on:
  push:
    branches: [main, master, pipfile-experiment]
  pull_request:
    types: [opened, closed]
    branches: [main, master, pipfile-experiment]

jobs:
  log:
    runs-on: ubuntu-latest
    env:
      PIPENV_PIPFILE: .github/workflows/Pipfile
      COMMIT_LOG_API: ${{ secrets.COMMIT_LOG_API }}
      GITHUB_LOGIN: ${{ github.actor }}
      COMMITS: ${{ toJSON(github.event.commits) }}
      REPOSITORY_URL: ${{ github.repositoryUrl }}
      EVENT_TYPE: ${{ github.event_name }}
      EVENT_ACTION: ${{ github.event.action }}
      PR_MERGED: ${{ github.event.pull_request.merged }}
      PR_CREATED_AT: ${{ github.event.pull_request.created_at }}
      PR_CLOSED_AT: ${{ github.event.pull_request.closed_at }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetches full history

      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        env:
          PIPENV_IGNORE_VIRTUALENVS: 1
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv install

      - name: Log pull request opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          pipenv run gitcommitlogger -r $(echo $REPOSITORY_URL) -t pull_request_opened -d $(echo $PR_CREATED_AT) -un $(echo $GITHUB_LOGIN) -o commit_stats.csv -u $(echo $COMMIT_LOG_API) -v

      - name: Log pull request closed and merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          echo $COMMITS > commits.json
          cat commits.json # debugging
          pipenv run gitcommitlogger -r $(echo $REPOSITORY_URL) -t pull_request_merged -d $(echo $PR_CLOSED_AT) -un $(echo $GITHUB_LOGIN) -i commits.json -o commit_stats.csv -u $(echo $COMMIT_LOG_API) -v

      - name: Log pull request closed without merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
        run: |
          pipenv run gitcommitlogger -r $(echo $REPOSITORY_URL) -t pull_request_closed -d $(echo $PR_CLOSED_AT) -un $(echo $GITHUB_LOGIN) -o commit_stats.csv -u $(echo $COMMIT_LOG_API) -v

      - name: Log push
        if: github.event_name == 'push'
        run: |
          echo $COMMITS > commits.json
          cat commits.json # debugging
          pipenv run gitcommitlogger -r $(echo $REPOSITORY_URL) -t $(echo $EVENT_TYPE) -i commits.json -o commit_stats.csv -u $(echo $COMMIT_LOG_API) -v

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Specify Python versions to test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        env:
          PIPENV_IGNORE_VIRTUALENVS: 1
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv

      - name: Install dependencies
        env:
          PIPENV_IGNORE_VIRTUALENVS: 1
        run: |
          pipenv install --dev

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pipenv run pytest tests/test_codeshakespeare.py -v
